~/sim_plat/apb/apb.sv
~/sim_plat/axi/axi-lite/axi_lite.sv
$proj_folder/testbench/pkg.sv
$proj_folder/testbench/i2c_tb.sv
$proj_folder/testbench/axi_iic_0_sim_netlist.v
$proj_folder/rtl/i2c_debounce.v
$proj_folder/rtl/i2c_slv.v
$proj_folder/rtl/i2c_reg.v
$proj_folder/rtl/sync_fifo.v
$proj_folder/rtl/i2c_core.v
$proj_folder/rtl/i2c_top.v
